version: '3.8'
services:

  main:
    build:
      context: ./main
      dockerfile: Dockerfile.main      
    depends_on:
      - redis 
    volumes:
      - ./main:/app
    environment:
      A_HOST: '0.0.0.0'
      A_PORT: 6000
      A_DEBUG: 1
    ports:
      - '5000:6000'

  redis:
    image: "redis:alpine"
    
